### PR TITLE
BIA-653: Adding PostgreSQL Test Cases for UserAuthorization View

### PR DESCRIPTION
**Pull request by nsd-daniel**
Creating PostgreSQLtesting cases, moving column match dictionary to every version of the DS and adjusting When_querying_the_UserAuthorization_view

### CODE REVIEW

**Comment by DavidJGapCR** [comment]
Since you didn't make any changes to `When_querying_the_UserAuthorization_view`, there are no Postgres tests running. This class needs to inherit from `When_querying_a_view_postgres`.

**Comment by DavidJGapCR** [comment]
There are a few cases that are not covered in our tests. You can work on that as part of this ticket, or you can create a new one.

DS 2: 
Line 47, when I change 'ALL' to something different like 'ALL1' no tests fail.
Line 49, when I change 'ALL' to something different like 'ALL1' no tests fail.
Line 81, when I comment out the first condition in the join.

DS 3.1 and potentially DS 3.2/Postgres:
Line 56, when I change 'ALL' to something different like 'ALL1' no tests fail.
Line 58, when I change 'ALL' to something different like 'ALL1' no tests fail.

**Comment by DavidJGapCR** [comment]
In relation to the file you added: `.../PostgreSQL/v_3_2/querying_SectionPermission_should_have_SectionKeyPermission.json`:

1. I don't think we need to duplicate this file, since the same one should work for MSSQL and Postgres, DS3.1 and 3.2 (Not DS 2)

2. This file needs to be called from `When_querying_the_UserAuthorization_view`, otherwise the file is not actually executed.

**Comment by nsd-daniel** [comment]
> Since you didn't make any changes to `When_querying_the_UserAuthorization_view`, there are no Postgres tests running. This class needs to inherit from `When_querying_a_view_postgres`.

Change done

**Comment by nsd-daniel** [comment]
> In relation to the file you added: `.../PostgreSQL/v_3_2/querying_SectionPermission_should_have_SectionKeyPermission.json`:
> 
> 1. I don't think we need to duplicate this file, since the same one should work for MSSQL and Postgres, DS3.1 and 3.2 (Not DS 2)
> 2. This file needs to be called from `When_querying_the_UserAuthorization_view`, otherwise the file is not actually executed.

change done

**Comment by nsd-daniel** [comment]
> There are a few cases that are not covered in our tests. You can work on that as part of this ticket, or you can create a new one.
> 
> DS 2:
> Line 47, when I change 'ALL' to something different like 'ALL1' no tests fail.
> Line 49, when I change 'ALL' to something different like 'ALL1' no tests fail.
> Line 81, when I comment out the first condition in the join.
> 
> DS 3.1 and potentially DS 3.2/Postgres:
> Line 56, when I change 'ALL' to something different like 'ALL1' no tests fail.
> Line 58, when I change 'ALL' to something different like 'ALL1' no tests fail.

will create another ticket to be sure this problem is correctly approached

**Review by bptillman — APPROVED** [review]
The work looks good now.

**Pull request merged**
