### PR TITLE
BIA-897: Updating tests project to support data standard 3.3. 

### PR DESCRIPTION
**Pull request by nsd-daniel**

### CODE REVIEW

**Comment by DavidJGapCR** [comment]
I made a commit to fix the build and some tests in the Operations section.

**Comment by DavidJGapCR** [comment]
@nsd-daniel,  can you please review the changes I made?
@jleiva-gap, can you review the code in general?
Thanks!

**Comment by DavidJGapCR** [comment]
It's ok that the dimension tests for the Data Standard 3.3 are failing. That will be fixed in this sprint.

**Comment by jleiva-gap** [comment]
Test are failing. The Dacpac for DS 3.3 is not working on TC.

```
OneTimeSetUp: Microsoft.SqlServer.Dac.DacServicesException : An error occurred during deployment plan generation. Deployment cannot continue.
  ----> Microsoft.Data.Tools.Schema.Sql.Deployment.DeploymentCompatibilityException : A project which specifies SQL Server 2019 or Azure SQL Database Managed Instance as the target platform cannot be published to SQL Server 2016.
```

**Review by DavidJGapCR — APPROVED** [review]

**Pull request merged**
